version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    tty: true
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - .:/caffe
    working_dir: /caffe

  db:
    image: mysql:8
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
