version: "3"

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/node/Dockerfile
    init: true
    tty: true
    ports:
      - 5555:5555
      - 3000:3000
    volumes:
      - .:/caffe
    working_dir: /caffe

  npc:
    build:
      context: .
      dockerfile: .devcontainer/npc/Dockerfile
    init: true
    tty: true
    volumes:
      - .:/caffe
    working_dir: /caffe

  db:
    image: mysql:8
    volumes:
      - ../db:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
