version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    tty: true
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - .:/caffe
    working_dir: /caffe

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: caffe
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
