name: Lint and Format

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint:fix

      - name: format
        run: pnpm format
