name: runs on Pull Request

on:
  pull_request:
    types:
      [opened, reopened, synchronize, review_requested, review_request_removed]
    branches:
      - develop
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  unanimously-approved:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: snow-actions/unanimously-approved@v2.1.0

  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint:fix

      - name: format
        run: pnpm format
