# coding: utf-8

"""
    Caffe Break API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from caffe_break_client.models.room_create200_response_phase import RoomCreate200ResponsePhase

class TestRoomCreate200ResponsePhase(unittest.TestCase):
    """RoomCreate200ResponsePhase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoomCreate200ResponsePhase:
        """Test RoomCreate200ResponsePhase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomCreate200ResponsePhase`
        """
        model = RoomCreate200ResponsePhase()
        if include_optional:
            return RoomCreate200ResponsePhase(
            )
        else:
            return RoomCreate200ResponsePhase(
        )
        """

    def testRoomCreate200ResponsePhase(self):
        """Test RoomCreate200ResponsePhase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
