# coding: utf-8

"""
    Caffe Break API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from caffe_break_client.models.room_create200_response import RoomCreate200Response

class TestRoomCreate200Response(unittest.TestCase):
    """RoomCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoomCreate200Response:
        """Test RoomCreate200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomCreate200Response`
        """
        model = RoomCreate200Response()
        if include_optional:
            return RoomCreate200Response(
                id = 'w8q6zgckec',
                password = 'k%?x!u'K}qz^',
                owner_id = 'w8q6zgckec',
                phase = None,
                players = [
                    caffe_break_client.models.room_create_200_response_players_inner.room_create_200_response_players_inner(
                        id = 'w8q6zgckec', 
                        name = 'k%?x!u'K}qz^', 
                        role = null, 
                        status = null, )
                    ],
                day = 0
            )
        else:
            return RoomCreate200Response(
                id = 'w8q6zgckec',
                password = 'k%?x!u'K}qz^',
                owner_id = 'w8q6zgckec',
                phase = None,
                players = [
                    caffe_break_client.models.room_create_200_response_players_inner.room_create_200_response_players_inner(
                        id = 'w8q6zgckec', 
                        name = 'k%?x!u'K}qz^', 
                        role = null, 
                        status = null, )
                    ],
                day = 0,
        )
        """

    def testRoomCreate200Response(self):
        """Test RoomCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
