# coding: utf-8

"""
    Caffe Break API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from caffe_break_client.models.player_create200_response_status import PlayerCreate200ResponseStatus

class TestPlayerCreate200ResponseStatus(unittest.TestCase):
    """PlayerCreate200ResponseStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerCreate200ResponseStatus:
        """Test PlayerCreate200ResponseStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerCreate200ResponseStatus`
        """
        model = PlayerCreate200ResponseStatus()
        if include_optional:
            return PlayerCreate200ResponseStatus(
            )
        else:
            return PlayerCreate200ResponseStatus(
        )
        """

    def testPlayerCreate200ResponseStatus(self):
        """Test PlayerCreate200ResponseStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
