# coding: utf-8

"""
    Caffe Break API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from caffe_break_client.models.room_create200_response_players_inner import RoomCreate200ResponsePlayersInner

class TestRoomCreate200ResponsePlayersInner(unittest.TestCase):
    """RoomCreate200ResponsePlayersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoomCreate200ResponsePlayersInner:
        """Test RoomCreate200ResponsePlayersInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomCreate200ResponsePlayersInner`
        """
        model = RoomCreate200ResponsePlayersInner()
        if include_optional:
            return RoomCreate200ResponsePlayersInner(
                id = 'w8q6zgckec',
                name = 'k%?x!u'K}qz^',
                role = None,
                status = None
            )
        else:
            return RoomCreate200ResponsePlayersInner(
                id = 'w8q6zgckec',
                name = 'k%?x!u'K}qz^',
                role = None,
                status = None,
        )
        """

    def testRoomCreate200ResponsePlayersInner(self):
        """Test RoomCreate200ResponsePlayersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
